package View;

import DAO.ThanhVienDAO;
import JDBCHelper.DatabaseConnection;
import Model.ThanhVien;
import java.awt.Image;
import java.io.File;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author xuant
 */
public class AccountManagement extends javax.swing.JPanel {

    boolean flag = false;

    String hinhAnh = "";
    
    int memberID;
    

    public AccountManagement(ThanhVien tv) {
        initComponents();
        hinhAnh = tv.getHinhAnh();
        memberID = tv.getMaTV();
        //gọi hàm hiển thị thông tin tv
        showDetail(tv);
    }

    //hàm hiển thị thông tin lên form
    private void showDetail(ThanhVien tv) {
        txtHoTen.setText(tv.getHoTen());
        txtHoTen.setEnabled(false);
        lblTaiKhoan.setText(tv.getTaiKhoan());
        txtMatKhau.setText(tv.getMatKhau());
        txtMatKhau.setEnabled(false);
        rdoNam.setSelected(tv.getGioiTinh().equals("Nam") || tv.getGioiTinh().equals("Male"));
        rdoNu.setSelected(tv.getGioiTinh().equals("Nữ") || tv.getGioiTinh().equals("Female"));
        txtEmail.setText(tv.getEmail());
        txtEmail.setEnabled(false);
        lblVaiTro.setText(tv.getMaVT() == 1 ? "Quản lý" : "Thành viên");
        lblNgayDangKy.setText(dateToString(tv.getNgayDangKy()));

        //hiển thị ảnh
        try {
            File file = new File("src\\Images\\" + hinhAnh);
            Image img = ImageIO.read(file);
            lblHinhAnh.setText(null);
            lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(215, 282, 0)));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        btnUpload.setEnabled(false);
    }

    //hàm kiểm tra dữ liệu nhập vào
    private boolean validateInfo(){
        JLabel jLabel[] = {lblHoTen, lblMatKhau, lblEmail};
        JTextField jTextField[] = {txtHoTen, txtMatKhau, txtEmail};
        for(int i = 0; i < jLabel.length; i++){
            if(jTextField[i].getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "Không để trống " + jLabel[i].getText());
                jTextField[i].requestFocus();
                return false;
            }
        }
        //kiểm tra mật khẩu
        if(String.valueOf(txtMatKhau.getPassword()).trim().length() < 6){
            JOptionPane.showMessageDialog(this, "Mật khẩu không đủ mạnh (>6 kí tự)");
            txtMatKhau.requestFocus();
            return false;
        }
        //kiểm tra email
        if(!txtEmail.getText().trim().endsWith("@fpt.edu.vn")){
            JOptionPane.showMessageDialog(this, "Sử dụng mail fpt");
            txtEmail.requestFocus();
            return false;
        }
        return true;
    }
    //hàm đổi date -> string
    private String dateToString(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(date);
    }

    //hàm cho phép cập nhật thông tin
    private void openUpdate() {
        txtHoTen.setEnabled(true);
        txtMatKhau.setEnabled(true);
        txtEmail.setEnabled(true);
         btnUpload.setEnabled(true);
    }
    //hàm đóng cập nhật thông tin
    private void closeUpdate() {
        txtHoTen.setEnabled(false);
        txtMatKhau.setEnabled(false);
        txtEmail.setEnabled(false);
        btnUpload.setEnabled(false);
    }

    //hàm lấy thông tin từ form
    private String[] getForm() {
        String[] info = new String[4];
        info[0] = txtHoTen.getText();
        info[1] = String.valueOf(txtMatKhau.getPassword());
        info[2] = txtEmail.getText();
        info[3] = hinhAnh;
        return info;
    }

    //update tv
    private boolean insert(int id, String[] s){
        int count = -1;
        String sql = "update ThanhVien set HoTen=?, MatKhau=?, Email=?, HinhAnh=? where MaTV=?";
        try(PreparedStatement ps = DatabaseConnection.getDBConnection().prepareStatement(sql)) {
            for(int i = 1; i <= 4; i++){
                ps.setString(i, s[i-1]);
            }
            ps.setInt(5, id);
            count = ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return count == 1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblEmail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        lblTaiKhoan = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        lblNgayDangKy = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(771, 626));
        setMinimumSize(new java.awt.Dimension(771, 626));
        setPreferredSize(new java.awt.Dimension(770, 626));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Account Management");

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setText("Image");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        lblHoTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoTen.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tài khoản");

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMatKhau.setText("Mật khẩu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Giới tính");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Vai trò");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ngày đăng ký");

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTaiKhoan.setText("jLabel10");

        lblVaiTro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVaiTro.setText("jLabel11");

        lblNgayDangKy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNgayDangKy.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTen)
                    .addComponent(jLabel4)
                    .addComponent(lblMatKhau)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(lblEmail)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCapNhat)
                    .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoNam)
                        .addGap(42, 42, 42)
                        .addComponent(rdoNu))
                    .addComponent(lblVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNgayDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail)
                    .addComponent(txtMatKhau)
                    .addComponent(txtHoTen))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel6, jLabel8, jLabel9, lblEmail, lblHoTen, lblMatKhau});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTaiKhoan))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblNgayDangKy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnCapNhat)
                .addGap(29, 29, 29))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel6, jLabel8, jLabel9, lblEmail, lblHoTen, lblMatKhau});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtHoTen, txtMatKhau});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(268, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnUpload))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpload)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if(!flag){
            openUpdate();
            flag = !flag;
        }else{
            if(!validateInfo()) return;
            //lấy thông tin mới từ form
            String info[] = getForm();
            //tiến hành cập nhật
            boolean check = insert(memberID, info);
            if(check){
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
                ThanhVien newTV = ThanhVienDAO.selectById(memberID);
                showDetail(newTV);
            }else{
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin thất bại!");
                return;
            }
            flag = !flag;
            closeUpdate();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jfc = new JFileChooser();
            int i = jfc.showOpenDialog(this);
            if (i == JFileChooser.APPROVE_OPTION) {
                File file = jfc.getSelectedFile();
                String path = file.getAbsolutePath();
                hinhAnh = path.substring(path.lastIndexOf("\\") + 1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgayDangKy;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
