package View;

import DAO.CapDoDAO;
import DAO.DeThiDAO;
import DAO.ThanhVienDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author xuant
 */
public class Display extends javax.swing.JPanel {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        //call method to show slogan
        showText();
        //gọi hàm hiển thị số lượng
        showCount();
    }

    private void showText() {
        new Thread() {
            @Override
            public void run() {
                String slogan[] = {"STOP", "THINKING", "START", "DOING"};
                while (true) {
                    String s = "";
                    for (int i = 0; i < slogan.length; i++) {
                        s += slogan[i] + " ";
                        lblSlogan.setText(s);
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
            }
        }.start();
    }

     //hàm hiển thị số lượng
    private void showCount(){
        //lấy số lượng thành viên
        int countMember = ThanhVienDAO.selectAll().size();
        String tv1 = lblThanhVien.getText();
        String tv2 = String.valueOf(countMember);
        String text1 = String.format("<html>%s<br/>%s</html>", tv1, tv2);
        lblThanhVien.setText(text1);
        //lấy số lượng cấp độ
        int countCapDo = CapDoDAO.selectAll().size();
        String cd1 = lblLevel.getText();
        String cd2 = String.valueOf(countCapDo);
        String text2 = String.format("<html>%s<br/>%s</html>", cd1, cd2);
        lblLevel.setText(text2);
        //lấy số lượng đề thi
        int countDeThi = DeThiDAO.getCount();
        String dt1 = lblDeThi.getText();
        String dt2 = String.valueOf(countDeThi);
        String text3 = String.format("<html>%s<br/>%s</html>", dt1, dt2);
        lblDeThi.setText(text3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblThanhVien = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblDeThi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSlogan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(771, 626));
        setMinimumSize(new java.awt.Dimension(771, 626));
        setPreferredSize(new java.awt.Dimension(770, 626));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        lblThanhVien.setBackground(new java.awt.Color(255, 0, 0));
        lblThanhVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThanhVien.setForeground(new java.awt.Color(255, 255, 255));
        lblThanhVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mb.png"))); // NOI18N
        lblThanhVien.setText("Thành viên");
        lblThanhVien.setOpaque(true);
        jPanel1.add(lblThanhVien);

        lblLevel.setBackground(new java.awt.Color(255, 0, 0));
        lblLevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lvl.png"))); // NOI18N
        lblLevel.setText("Level");
        lblLevel.setOpaque(true);
        jPanel1.add(lblLevel);

        lblDeThi.setBackground(new java.awt.Color(255, 0, 0));
        lblDeThi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDeThi.setForeground(new java.awt.Color(255, 255, 255));
        lblDeThi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DT.png"))); // NOI18N
        lblDeThi.setText("Đề thi");
        lblDeThi.setOpaque(true);
        jPanel1.add(lblDeThi);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSlogan.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(204, 0, 0));
        lblSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan.setText("NO PAIN NO GAIN");
        jPanel2.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 500, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cg.gif"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 500, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_bl.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDeThi;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblThanhVien;
    // End of variables declaration//GEN-END:variables
}
