package View;

import Model.ThanhVien;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author xuant
 */
public class MainDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MainDisplay
     */
    ThanhVien member;

    public MainDisplay(ThanhVien tv) {
        initComponents();
        member = tv;
        setRole(tv.getMaVT());
        setColorButton();
        setAction();
        showMember(tv);
        System.out.println(this.getWidth() + " " + this.getHeight());
    }

    private void setColorButton() {
        JButton jButton[] = {btnMain, btnTest, btnQLTV, btnQLDT, btnTKDL};
        for (JButton jb : jButton) {
            jb.setBackground(new Color(178, 34, 34));
            jb.setForeground(Color.white);
            jb.setFont(new Font("Tahoma", Font.BOLD, 14));
        }
    }

    private void showMember(ThanhVien tv) {
        try {
            File file = new File("src\\Images\\" + tv.getHinhAnh());
            Image img = ImageIO.read(file);
            int width = lblImage.getWidth();
            int height = lblImage.getHeight();
            lblImage.setText(null);
            lblImage.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
            lblName.setText(tv.getHoTen());

            //hiển thị tab màn hình chính
            if (tbpMain.getTabCount() != 0) {
                tbpMain.removeAll();
            }
            Display display = new Display();
            tbpMain.addTab("Màn hình chính", display);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setAction() {
        JButton jButton[] = {btnMain, btnTest, btnQLTV, btnQLDT, btnTKDL};
        for (JButton jb : jButton) {
            jb.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    jb.setBackground(new Color(205, 173, 0));
                    jb.setForeground(Color.white);
                    jb.setFont(new Font("Tahoma", Font.BOLD, 14));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    jb.setBackground(new Color(178, 34, 34));
                    jb.setForeground(Color.white);
                    jb.setFont(new Font("Tahoma", Font.BOLD, 14));
                }
            });
        }
    }

    private void setRole(int role) {
        if (role == 2) {
            btnQLTV.setText("Quản lý tài khoản");
            btnQLTV.setActionCommand("Quản lý tài khoản");
            btnQLDT.setText("Lịch sử thi");
            btnQLDT.setActionCommand("Lịch sử thi");
            btnTKDL.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMain = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        btnQLTV = new javax.swing.JButton();
        btnQLDT = new javax.swing.JButton();
        btnTKDL = new javax.swing.JButton();
        tbpMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("English Poly");
        setMinimumSize(new java.awt.Dimension(1010, 685));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(209, 238, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Image");
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(122, 139, 139));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));

        btnMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main.png"))); // NOI18N
        btnMain.setText("Màn hình chính");
        btnMain.setOpaque(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnMain, org.jdesktop.beansbinding.ELProperty.create("Màn hình chính"), btnMain, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        jPanel2.add(btnMain);

        btnTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Test.png"))); // NOI18N
        btnTest.setText("Thi ngay đi");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnTest, org.jdesktop.beansbinding.ELProperty.create("Thi ngay đi"), btnTest, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        jPanel2.add(btnTest);

        btnQLTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLTV.png"))); // NOI18N
        btnQLTV.setText("Quản lý thành viên");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnQLTV, org.jdesktop.beansbinding.ELProperty.create("Quản lý thành viên"), btnQLTV, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnQLTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTVActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLTV);

        btnQLDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLDT.png"))); // NOI18N
        btnQLDT.setText("Quản lý đề thi");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnQLDT, org.jdesktop.beansbinding.ELProperty.create("Quản lý đề thi"), btnQLDT, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnQLDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDTActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLDT);

        btnTKDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TK.png"))); // NOI18N
        btnTKDL.setText("Thống kê dữ liệu");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnTKDL, org.jdesktop.beansbinding.ELProperty.create("Thống kê dữ liệu"), btnTKDL, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnTKDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKDLActionPerformed(evt);
            }
        });
        jPanel2.add(btnTKDL);

        tbpMain.setMaximumSize(new java.awt.Dimension(771, 626));
        tbpMain.setMinimumSize(new java.awt.Dimension(771, 626));
        tbpMain.setPreferredSize(new java.awt.Dimension(771, 626));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        try {
            if (tbpMain.getTabCount() != 0) {
                tbpMain.removeAll();
            }
            Display display = new Display();
            tbpMain.addTab("Màn hình chính", display);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMainActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        try {
            if (tbpMain.getTabCount() != 0) {
                tbpMain.removeAll();
            }
            TestDisplay testDisplay = new TestDisplay(member);
            tbpMain.addTab("Test", testDisplay);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnQLTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTVActionPerformed
        try {
            String cmd = btnQLTV.getActionCommand();
            if (cmd.equals("Quản lý thành viên")) {
                if (tbpMain.getTabCount() != 0) {
                    tbpMain.removeAll();
                }
                MemberManagement mm = new MemberManagement();
                tbpMain.addTab("Quản lý thành viên", mm);
            }
            if (cmd.equals("Quản lý tài khoản")) {
                if (tbpMain.getTabCount() != 0) {
                    tbpMain.removeAll();
                }
                AccountManagement am = new AccountManagement(member);
                tbpMain.addTab("Quản lý tài khoản", am);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnQLTVActionPerformed

    private void btnTKDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKDLActionPerformed
        try {
            String cmd = btnTKDL.getActionCommand();
            if (cmd.equals("Thống kê dữ liệu")) {
                if (tbpMain.getTabCount() != 0) {
                    tbpMain.removeAll();
                }
                Reporter rp = new Reporter();
                tbpMain.addTab("Thống kê", rp);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTKDLActionPerformed

    private void btnQLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDTActionPerformed
        try {
            String cmd = btnQLDT.getActionCommand();
            if (cmd.equals("Quản lý đề thi")) {
                if (tbpMain.getTabCount() != 0) {
                    tbpMain.removeAll();
                }
                ExamManagement em = new ExamManagement();
                tbpMain.addTab("Quản lý đề thi", em);
            }
            if (cmd.equals("Lịch sử thi")) {
                if (tbpMain.getTabCount() != 0) {
                    tbpMain.removeAll();
                }
                History history = new History();
                tbpMain.addTab("Lịch sử thi", history);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnQLDTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnQLDT;
    private javax.swing.JButton btnQLTV;
    private javax.swing.JButton btnTKDL;
    private javax.swing.JButton btnTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JTabbedPane tbpMain;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
