package MDIView;

import DAO.FormDAO;
import DAO.ThanhVienDAO;
import static DAO.ThanhVienDAO.writeFile;
import Model.ThanhVien;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author xuant
 */
public class MemberManagement extends javax.swing.JPanel {

    /**
     * Creates new form Display
     */
    DefaultTableModel model;

    TableRowSorter<TableModel> rowSorter = null;

    int index;

    List<ThanhVien> list;

    JDesktopPane jDesktopPane;

    public MemberManagement(JDesktopPane jdk) {
        initComponents();
        jDesktopPane = jdk;
        model = (DefaultTableModel) tblMember.getModel();
        //gọi hàm đổ dữ liệu thành viên lên bảng
        fillTable();

        //gọi hàm thêm sự kiện search
        search();
    }

    //hàm đổ dữ liệu thành viên lên bảng
    private void fillTable() {
        //lấy dữ liệu từ database
        list = ThanhVienDAO.selectAll();
        //đổ vào model

        model.setRowCount(0);
        int flag = 1;
        for (ThanhVien tv : list) {
            model.addRow(new Object[]{
                flag++, tv.getHoTen(), tv.getGioiTinh(), tv.getEmail(), tv.getHinhAnh(), tv.getNgayDangKy()
            });
        }
    }

    //hàm search
    private void search() {
        rowSorter = new TableRowSorter<>(model);
        tblMember.setRowSorter(rowSorter);
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                String text = txtSearch.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(751, 630));
        setMinimumSize(new java.awt.Dimension(751, 630));
        setPreferredSize(new java.awt.Dimension(770, 626));

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));

        txtSearch.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setText("Search...");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_flag_black_24dp.png"))); // NOI18N
        btnDelete.setText("Xóa thành viên");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(204, 0, 0));
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_flag_black_24dp.png"))); // NOI18N
        btnReport.setText("Xuất báo cáo");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport)
                .addGap(51, 51, 51)
                .addComponent(btnDelete)
                .addGap(80, 80, 80))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnReport});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReport)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnReport});

        tblMember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ Tên", "Giới tính", "Email", "Hình ảnh", "Ngày đăng ký"
            }
        ));
        tblMember.setRowHeight(40);
        tblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMember);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText(null);
    }//GEN-LAST:event_txtSearchMouseClicked

    private void tblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberMouseClicked
        try {
            index = tblMember.getSelectedRow();
            index = Integer.parseInt(String.valueOf(tblMember.getValueAt(index, 0)));
            ThanhVien tv = list.get(index - 1);
            AccountInfo ai = new AccountInfo(tv);
            ai.setVisible(true);
            jDesktopPane.add(ai);
            FormDAO.centerJIF(jDesktopPane, ai);
            try {
                ai.setSelected(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblMemberMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            Object[] mes = {"Cạch mặt luôn", "Thôi tha cho nó"};
            int option = JOptionPane.showOptionDialog(null, "Bạn muốn xóa thành viên này?", "Notice!", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, mes, mes[0]);
            if (option == 0) {
                //lấy mã thành viên
                index = tblMember.getSelectedRow();
                index = Integer.parseInt(String.valueOf(tblMember.getValueAt(index, 0)));
                ThanhVien tv = list.get(index - 1);
                boolean res = ThanhVienDAO.delete(tv.getMaTV());
                if (res) {
                    JOptionPane.showMessageDialog(this, "Bạn không phải nhìn thấy mặt nó nữa!");
                    //đổ lại dữ liệu lên bảng
                    fillTable();
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Gặp sự cố rồi, quay lại sau nhé");
                    return;
                }
            }
            if (option == 1) {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Thành viên");
            //create header
            ThanhVienDAO.writeHeader(sheet, 0);

            //create data
            ThanhVienDAO.writeData(sheet, list);
            //Auto resize column witdth
            int num = sheet.getRow(0).getPhysicalNumberOfCells();
            ThanhVienDAO.autosizeColumn(sheet, num);
            //ghi file
            final String path = "E:/thanhvien.xlsx";
            ThanhVienDAO.writeFile(path, workbook);
            JOptionPane.showMessageDialog(this, "Ghi file excel thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ghi file excel thất bại!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReport;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
