/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDIView;

import DAO.CauHoiDAO;
import Model.CauHoi;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author xuant
 */
public class NewQuestion extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewQuestion
     */
    CauHoi cauHoi = new CauHoi();

    CauHoi update;
    String s = "";

    public NewQuestion(int maDT, int maNCH) {
        initComponents();
        cauHoi.setMaDT(maDT);
        cauHoi.setMaNCH(maNCH);
        cauHoi.setMaCH(CauHoiDAO.getLastId() + 1);
    }

    public NewQuestion(CauHoi ch) {
         initComponents();
        update = ch;
        showDetail(ch);
        btnThem.setText("Sửa");
    }

    private void showDetail(CauHoi ch) {
        txtContent.setText(ch.getDoanVan());
        txtQuestion.setText(ch.getNoiDungCH());
        txtDapAnA.setText(ch.getDapAnA());
        txtDapAnB.setText(ch.getDapAnB());
        txtDapAnC.setText(ch.getDapAnC());
        txtDapAnD.setText(ch.getDapAnD());
        txtCorrect.setText(ch.getDapAnDung());
        rdoEasy.setSelected(ch.getCapDo().equals("Easy"));
        rdoMedium.setSelected(ch.getCapDo().equals("Medium"));
        rdoHard.setSelected(ch.getCapDo().equals("Hard"));
        rdoSingle.setSelected(ch.getMaLCH() == 1);
        rdoMulti.setSelected(ch.getMaLCH() == 2);
        rdoFill.setSelected(ch.getMaLCH() == 3);
    }

    //hàm lấy dữ liệu từ form
    private void getForm(CauHoi cauHoi) {
        String content = txtContent.getText();
        if (content.trim().length() == 0) {
            content = "";
        }
        cauHoi.setDoanVan(content);

        cauHoi.setAmThanh(s);

        cauHoi.setNoiDungCH(txtQuestion.getText().trim().length() == 0 ? "" : txtQuestion.getText().trim());

        cauHoi.setDapAnA(txtDapAnA.getText().trim().length() == 0 ? "" : txtDapAnA.getText().trim());
        cauHoi.setDapAnB(txtDapAnB.getText().trim().length() == 0 ? "" : txtDapAnB.getText().trim());
        cauHoi.setDapAnC(txtDapAnC.getText().trim().length() == 0 ? "" : txtDapAnC.getText().trim());
        cauHoi.setDapAnD(txtDapAnD.getText().trim().length() == 0 ? "" : txtDapAnD.getText().trim());
        cauHoi.setDapAnDung(txtCorrect.getText().trim().length() == 0 ? "" : txtCorrect.getText().trim());
        cauHoi.setCapDo(buttonGroup1.getSelection().getActionCommand());
        cauHoi.setMaLCH(Integer.parseInt(buttonGroup2.getSelection().getActionCommand()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDapAnA = new javax.swing.JTextField();
        txtDapAnC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDapAnB = new javax.swing.JTextField();
        txtDapAnD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorrect = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rdoEasy = new javax.swing.JRadioButton();
        rdoMedium = new javax.swing.JRadioButton();
        rdoHard = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rdoSingle = new javax.swing.JRadioButton();
        rdoMulti = new javax.swing.JRadioButton();
        rdoFill = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Content");

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jLabel2.setText("Audio");

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        jLabel3.setText("Nội dung");

        jLabel4.setText("Đáp án A");

        jLabel5.setText("Đáp án C");

        jLabel6.setText("Đáp án B");

        jLabel7.setText("Đáp án D");

        jLabel8.setText("Đáp án đúng");

        jLabel9.setText("Độ khó");

        buttonGroup1.add(rdoEasy);
        rdoEasy.setSelected(true);
        rdoEasy.setText("Easy");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoEasy, org.jdesktop.beansbinding.ELProperty.create("Easy"), rdoEasy, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup1.add(rdoMedium);
        rdoMedium.setText("Medium");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoMedium, org.jdesktop.beansbinding.ELProperty.create("Medium"), rdoMedium, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup1.add(rdoHard);
        rdoHard.setText("Hard");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoHard, org.jdesktop.beansbinding.ELProperty.create("Hard"), rdoHard, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jLabel10.setText("Loại CH");

        buttonGroup2.add(rdoSingle);
        rdoSingle.setSelected(true);
        rdoSingle.setText("Single Choice");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoSingle, org.jdesktop.beansbinding.ELProperty.create("1"), rdoSingle, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup2.add(rdoMulti);
        rdoMulti.setText("Multi Choice");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoMulti, org.jdesktop.beansbinding.ELProperty.create("2"), rdoMulti, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup2.add(rdoFill);
        rdoFill.setText("Fill in the blank");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rdoFill, org.jdesktop.beansbinding.ELProperty.create("3"), rdoFill, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnThem.setText("Thêm");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnThem, org.jdesktop.beansbinding.ELProperty.create("Add"), btnThem, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtQuestion)
                            .addComponent(btnUpload)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDapAnA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDapAnC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDapAnB, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(txtDapAnD)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoSingle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoMulti))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoEasy)
                                        .addGap(46, 46, 46)
                                        .addComponent(rdoMedium))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHuyBo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoHard)
                                    .addComponent(rdoFill))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCorrect, txtDapAnA, txtDapAnB, txtDapAnC, txtDapAnD});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuyBo, btnThem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnUpload))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDapAnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDapAnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDapAnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDapAnD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdoEasy)
                    .addComponent(rdoMedium)
                    .addComponent(rdoHard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rdoSingle)
                    .addComponent(rdoMulti)
                    .addComponent(rdoFill))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnHuyBo))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCorrect, txtDapAnA, txtDapAnB, txtDapAnC, txtDapAnD});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHuyBo, btnThem});

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        try {
            JFileChooser jfc = new JFileChooser();
            int i = jfc.showOpenDialog(this);
            if (i == JFileChooser.APPROVE_OPTION) {
                File file = jfc.getSelectedFile();
                String path = file.getAbsolutePath();
                s = path.substring(path.lastIndexOf("\\") + 1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            String action = btnThem.getText();
            if (action.equals("Thêm")) {
                getForm(cauHoi);
                CauHoiDAO.insert(cauHoi);
                JOptionPane.showMessageDialog(this, "Thêm câu hỏi thành công!");
                this.dispose();
            }else{
                getForm(update);
                CauHoiDAO.update(update);
                JOptionPane.showMessageDialog(this, "Sửa câu hỏi thành công!");
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoEasy;
    private javax.swing.JRadioButton rdoFill;
    private javax.swing.JRadioButton rdoHard;
    private javax.swing.JRadioButton rdoMedium;
    private javax.swing.JRadioButton rdoMulti;
    private javax.swing.JRadioButton rdoSingle;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtCorrect;
    private javax.swing.JTextField txtDapAnA;
    private javax.swing.JTextField txtDapAnB;
    private javax.swing.JTextField txtDapAnC;
    private javax.swing.JTextField txtDapAnD;
    private javax.swing.JTextField txtQuestion;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
