package MDIView;

import DAO.FormDAO;
import Model.ThanhVien;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author xuant
 */
public class TestDisplay extends javax.swing.JPanel {

    /**
     * Creates new form TestDisplay
     */
    ThanhVien member;

    JDesktopPane jDesktopPane;

    public TestDisplay(ThanhVien tv, JDesktopPane jdk) {
        initComponents();
        member = tv;
        jDesktopPane = jdk;
        //add method to add mouselistener
        setAction();
    }

    private void setAction() {
        JButton btn[] = {btnEnglish11, btnEnglish12, btnEnglish21, btnEnglish22};
        for (JButton jb : btn) {
            jb.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                    int count = tbpTest.getTabCount();
                    if (count != 0) {
                        Object[] mes = {"Tiếp tục thi", "Làm bài mới"};
                        int option = JOptionPane.showOptionDialog(null, "Bạn đang trong bài thi, bạn có muốn?", "Notice!", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, mes, mes[0]);
                        if (option == 0) {
                            return;
                        }
                        if (option == 1) {
                            try {
                                tbpTest.removeAll();
                                LoadingDisplay ld = new LoadingDisplay(TestDisplay.this, jb.getText(), member, jDesktopPane);
                                ld.setVisible(true);
                                jDesktopPane.add(ld);
                                FormDAO.centerJIF(jDesktopPane, ld);
                                try {
                                    ld.setSelected(true);
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                    } else {
                        Object[] mes = {"Sẵn sàng rồi bạn ơi", "Chưa sẵn sàng lắm"};
                        int option = JOptionPane.showOptionDialog(null, "Bạn đã sẵn sàng bắt đầu bài thi?", "Notice!", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, mes, mes[0]);
                        if (option == 0) {
                            LoadingDisplay ld = new LoadingDisplay(TestDisplay.this, jb.getText(), member, jDesktopPane);
                            ld.setVisible(true);
                            jDesktopPane.add(ld);
                            FormDAO.centerJIF(jDesktopPane, ld);
                            try {
                                ld.setSelected(true);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                        if (option == 1) {
                            return;
                        }

                    }
                }

                @Override
                public void mousePressed(MouseEvent me) {
                }

                @Override
                public void mouseReleased(MouseEvent me) {
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    jb.setBackground(new Color(205, 173, 0));
                    jb.setForeground(Color.white);
                    jb.setFont(new Font("Tahoma", Font.BOLD, 14));
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    jb.setBackground(new Color(178, 34, 134));
                    jb.setForeground(Color.white);
                    jb.setFont(new Font("Tahoma", Font.BOLD, 14));
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEnglish11 = new javax.swing.JButton();
        btnEnglish12 = new javax.swing.JButton();
        btnEnglish21 = new javax.swing.JButton();
        btnEnglish22 = new javax.swing.JButton();
        tbpTest = new javax.swing.JTabbedPane();

        setMaximumSize(new java.awt.Dimension(751, 630));
        setMinimumSize(new java.awt.Dimension(75, 63));
        setPreferredSize(new java.awt.Dimension(751, 630));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 0, 10));

        btnEnglish11.setBackground(new java.awt.Color(178, 34, 134));
        btnEnglish11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnglish11.setForeground(new java.awt.Color(255, 255, 255));
        btnEnglish11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.1.png"))); // NOI18N
        btnEnglish11.setText("Tiếng Anh 1.1");
        jPanel1.add(btnEnglish11);

        btnEnglish12.setBackground(new java.awt.Color(178, 34, 134));
        btnEnglish12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnglish12.setForeground(new java.awt.Color(255, 255, 255));
        btnEnglish12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.2.png"))); // NOI18N
        btnEnglish12.setText("Tiếng Anh 1.2");
        jPanel1.add(btnEnglish12);

        btnEnglish21.setBackground(new java.awt.Color(178, 34, 134));
        btnEnglish21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnglish21.setForeground(new java.awt.Color(255, 255, 255));
        btnEnglish21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.1.png"))); // NOI18N
        btnEnglish21.setText("Tiếng Anh 2.1");
        jPanel1.add(btnEnglish21);

        btnEnglish22.setBackground(new java.awt.Color(178, 34, 134));
        btnEnglish22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnglish22.setForeground(new java.awt.Color(255, 255, 255));
        btnEnglish22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.2.png"))); // NOI18N
        btnEnglish22.setText("Tiếng Anh 2.2");
        jPanel1.add(btnEnglish22);

        tbpTest.setPreferredSize(new java.awt.Dimension(770, 517));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpTest, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpTest, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTabbedPane getTbpTest() {
        return tbpTest;
    }

    public void setTbpTest(JTabbedPane tbpTest) {
        this.tbpTest = tbpTest;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnglish11;
    private javax.swing.JButton btnEnglish12;
    private javax.swing.JButton btnEnglish21;
    private javax.swing.JButton btnEnglish22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tbpTest;
    // End of variables declaration//GEN-END:variables
}
